universe   = vanilla
executable = run.sh
arguments  = pT4l Run3 24
output     = logs/$(ClusterId).$(Process).out
error      = logs/$(ClusterId).$(Process).err
log        = logs/$(ClusterId).$(Process).log

+JobFlavour = "testmatch"

transfer_input_files = /afs/cern.ch/work/l/lurda/HZZ/CMSSW_14_1_0_pre4/src/FiducialXSFWK/coefficients/RunCoefficients.py
should_transfer_files = YES
when_to_transfer_output = ON_EXIT

queue
